/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#28161d",
        "on-secondary-fixed-variant": "#3e4a36",
        "surface-container-highest": "#e5e2dd",
        "on-tertiary-fixed-variant": "#574148",
        "secondary-fixed-dim": "#bdcbb1",
        "inverse-surface": "#31302d",
        "secondary": "#55624d",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c4c8bf",
        "tertiary-fixed-dim": "#ddbfc7",
        "primary-container": "#a8b5a2",
        "primary": "#566252",
        "surface-dim": "#dcdad5",
        "secondary-container": "#d6e4c9",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#1c1c19",
        "surface": "#fcf9f4",
        "on-secondary-container": "#5a6651",
        "inverse-primary": "#bdcab7",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3e4a3b",
        "primary-fixed-dim": "#bdcab7",
        "on-surface-variant": "#444842",
        "tertiary-fixed": "#fadbe3",
        "surface-bright": "#fcf9f4",
        "on-background": "#1c1c19",
        "surface-tint": "#566252",
        "on-secondary-fixed": "#131e0e",
        "surface-container-low": "#f6f3ee",
        "inverse-on-surface": "#f3f0eb",
        "tertiary-container": "#c7aab2",
        "outline": "#757871",
        "on-error": "#ffffff",
        "surface-variant": "#e5e2dd",
        "surface-container": "#f0ede8",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d9e7cc",
        "on-primary-container": "#3b4738",
        "on-primary-fixed": "#141e12",
        "tertiary": "#70585f",
        "surface-container-high": "#ebe8e3",
        "on-tertiary-container": "#543e45",
        "background": "#fcf9f4",
        "error-container": "#ffdad6",
        "primary-fixed": "#d9e6d2",
        "error": "#ba1a1a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
      },
      keyframes: {
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        slideUp: {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
